#!/usr/bin/env node
//
// Turn the desktop's theme tokens into Swift.
//
// §52 asks for one design token system across the platforms rather than an iOS
// theme that drifts from the desktop one. The desktop's tokens are CSS custom
// properties on `:root`, which is the right home for them — a user theme is a
// short file that redefines a few, not a fork of the stylesheet. So this reads
// that file and emits the same values as Swift, and CI fails if the committed
// output is stale.
//
// Only colours and dimensions cross. Anything genuinely per-platform — a font
// stack, a shadow — stays where it belongs, because iOS has its own answers
// (Dynamic Type, system materials) and forcing the desktop's would be worse
// than not sharing at all.
//
//   node ios/Scripts/generate-tokens.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../..');
const source = resolve(repoRoot, 'src/styles/theme.css');
// An explicit destination lets the freshness check generate elsewhere and
// compare, instead of overwriting what it is checking.
const output = process.argv[2]
  ? resolve(process.argv[2])
  : resolve(repoRoot, 'ios/Services/DesignTokens.swift');

const css = readFileSync(source, 'utf8');

/** Pull the declarations out of one selector block. */
function block(selector) {
  // Deliberately not a CSS parser: the file is ours, its shape is stable, and
  // a dependency to read twelve declarations would be worse than a regex with
  // a test behind it.
  const start = css.indexOf(selector);
  if (start === -1) throw new Error(`no ${selector} block in theme.css`);
  const open = css.indexOf('{', start);
  const close = css.indexOf('}', open);
  if (open === -1 || close === -1) throw new Error(`malformed ${selector} block`);

  const declarations = new Map();
  for (const line of css.slice(open + 1, close).split('\n')) {
    const match = line.match(/^\s*--([\w-]+)\s*:\s*([^;]+);/);
    if (match) declarations.set(match[1], match[2].trim());
  }
  return declarations;
}

const dark = block(':root {');
const light = block(":root[data-theme='light']");

/** `--background-primary` → `backgroundPrimary` */
const camel = (name) => name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

/** Resolve `var(--x)` one level, which is as deep as the file goes. */
function resolveValue(value, table, fallback) {
  const reference = value.match(/^var\(--([\w-]+)\)$/);
  if (!reference) return value;
  return table.get(reference[1]) ?? fallback.get(reference[1]) ?? value;
}

/** `#rrggbb`, `#rgb` or `rgba(r, g, b, a)` → Swift Color components. */
function swiftColor(value) {
  const hex = value.match(/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/);
  if (hex) {
    const digits = hex[1].length === 3
      ? hex[1].split('').map((c) => c + c).join('')
      : hex[1];
    const [r, g, b] = [0, 2, 4].map((i) => parseInt(digits.slice(i, i + 2), 16) / 255);
    return { r, g, b, a: 1 };
  }
  const rgba = value.match(/^rgba?\(([^)]+)\)$/);
  if (rgba) {
    const parts = rgba[1].split(',').map((p) => parseFloat(p.trim()));
    if (parts.length >= 3) {
      return { r: parts[0] / 255, g: parts[1] / 255, b: parts[2] / 255, a: parts[3] ?? 1 };
    }
  }
  return null;
}

/** `8px` / `1.5rem` → points. */
function swiftLength(value) {
  const px = value.match(/^(-?[\d.]+)px$/);
  if (px) return parseFloat(px[1]);
  const rem = value.match(/^(-?[\d.]+)rem$/);
  if (rem) return parseFloat(rem[1]) * 16;
  return null;
}

const colors = [];
const lengths = [];

for (const [name, rawDark] of dark) {
  const darkValue = resolveValue(rawDark, dark, dark);
  const lightValue = resolveValue(light.get(name) ?? rawDark, light, dark);

  const darkColor = swiftColor(darkValue);
  const lightColor = swiftColor(lightValue);
  if (darkColor && lightColor) {
    colors.push({ name: camel(name), token: name, dark: darkColor, light: lightColor });
    continue;
  }

  const length = swiftLength(darkValue);
  if (length !== null) lengths.push({ name: camel(name), token: name, value: length });
}

colors.sort((a, b) => a.name.localeCompare(b.name));
lengths.sort((a, b) => a.name.localeCompare(b.name));

const f = (n) => Number(n.toFixed(4)).toString();

const swift = `// Generated by ios/Scripts/generate-tokens.mjs from src/styles/theme.css.
// Do not edit: change the CSS and regenerate. CI fails if this file is stale.
//
// ${colors.length} colours and ${lengths.length} dimensions, shared with the
// desktop so "the accent colour" means one value on every platform rather than
// two that drift.

import SwiftUI

enum DesignTokens {
    /// A colour that follows the interface style, the same pair the desktop
    /// theme defines for dark and light.
    struct Token {
        let light: Color
        let dark: Color

        /// Resolved against the current trait collection, so it updates when
        /// the user switches appearance without the view having to know.
        var color: Color {
            Color(UIColor { traits in
                UIColor(traits.userInterfaceStyle == .dark ? dark : light)
            })
        }
    }

    // MARK: - Colours

${colors
  .map(
    (c) => `    /// \`--${c.token}\`
    static let ${c.name} = Token(
        light: Color(red: ${f(c.light.r)}, green: ${f(c.light.g)}, blue: ${f(c.light.b)}, opacity: ${f(c.light.a)}),
        dark: Color(red: ${f(c.dark.r)}, green: ${f(c.dark.g)}, blue: ${f(c.dark.b)}, opacity: ${f(c.dark.a)})
    )`
  )
  .join('\n\n')}

    // MARK: - Dimensions

${lengths.map((l) => `    /// \`--${l.token}\`\n    static let ${l.name}: CGFloat = ${f(l.value)}`).join('\n\n')}
}

extension ShapeStyle where Self == Color {
    /// \`Text("x").foregroundStyle(.token(.textMuted))\`
    static func token(_ token: DesignTokens.Token) -> Color { token.color }
}
`;

writeFileSync(output, swift);
console.log(`${colors.length} colours, ${lengths.length} dimensions → ios/Services/DesignTokens.swift`);
