// Generated by ios/Scripts/generate-tokens.mjs from src/styles/theme.css.
// Do not edit: change the CSS and regenerate. CI fails if this file is stale.
//
// 43 colours and 15 dimensions, shared with the
// desktop so "the accent colour" means one value on every platform rather than
// two that drift.

import SwiftUI

enum DesignTokens {
    /// A colour that follows the interface style, the same pair the desktop
    /// theme defines for dark and light.
    struct Token {
        let light: Color
        let dark: Color

        /// Resolved against the current trait collection, so it updates when
        /// the user switches appearance without the view having to know.
        var color: Color {
            Color(UIColor { traits in
                UIColor(traits.userInterfaceStyle == .dark ? dark : light)
            })
        }
    }

    // MARK: - Colours

    /// `--accent`
    static let accent = Token(
        light: Color(red: 0.2314, green: 0.4353, blue: 0.8314, opacity: 1),
        dark: Color(red: 0.4784, green: 0.6353, blue: 0.9686, opacity: 1)
    )

    /// `--accent-hover`
    static let accentHover = Token(
        light: Color(red: 0.1843, green: 0.3608, blue: 0.7098, opacity: 1),
        dark: Color(red: 0.5765, green: 0.7059, blue: 1, opacity: 1)
    )

    /// `--accent-muted`
    static let accentMuted = Token(
        light: Color(red: 0.2314, green: 0.4353, blue: 0.8314, opacity: 0.16),
        dark: Color(red: 0.4784, green: 0.6353, blue: 0.9686, opacity: 0.22)
    )

    /// `--background-modifier-active`
    static let backgroundModifierActive = Token(
        light: Color(red: 0.2314, green: 0.4353, blue: 0.8314, opacity: 0.12),
        dark: Color(red: 0.4784, green: 0.6353, blue: 0.9686, opacity: 0.16)
    )

    /// `--background-modifier-border`
    static let backgroundModifierBorder = Token(
        light: Color(red: 0.8863, green: 0.898, blue: 0.9176, opacity: 1),
        dark: Color(red: 0.1686, green: 0.1843, blue: 0.2196, opacity: 1)
    )

    /// `--background-modifier-error`
    static let backgroundModifierError = Token(
        light: Color(red: 0.7843, green: 0.2157, blue: 0.2588, opacity: 0.1),
        dark: Color(red: 0.9137, green: 0.4157, blue: 0.4549, opacity: 0.15)
    )

    /// `--background-modifier-hover`
    static let backgroundModifierHover = Token(
        light: Color(red: 0, green: 0, blue: 0, opacity: 0.045),
        dark: Color(red: 1, green: 1, blue: 1, opacity: 0.05)
    )

    /// `--background-modifier-success`
    static let backgroundModifierSuccess = Token(
        light: Color(red: 0.1333, green: 0.5255, blue: 0.3059, opacity: 0.12),
        dark: Color(red: 0.4941, green: 0.7843, blue: 0.5843, opacity: 0.15)
    )

    /// `--background-primary`
    static let backgroundPrimary = Token(
        light: Color(red: 1, green: 1, blue: 1, opacity: 1),
        dark: Color(red: 0.0863, green: 0.0941, blue: 0.1137, opacity: 1)
    )

    /// `--background-primary-alt`
    static let backgroundPrimaryAlt = Token(
        light: Color(red: 0.9804, green: 0.9843, blue: 0.9882, opacity: 1),
        dark: Color(red: 0.102, green: 0.1137, blue: 0.1373, opacity: 1)
    )

    /// `--background-secondary`
    static let backgroundSecondary = Token(
        light: Color(red: 0.9569, green: 0.9608, blue: 0.9686, opacity: 1),
        dark: Color(red: 0.1137, green: 0.1255, blue: 0.1529, opacity: 1)
    )

    /// `--background-secondary-alt`
    static let backgroundSecondaryAlt = Token(
        light: Color(red: 0.9255, green: 0.9333, blue: 0.9451, opacity: 1),
        dark: Color(red: 0.1373, green: 0.149, blue: 0.1804, opacity: 1)
    )

    /// `--border`
    static let border = Token(
        light: Color(red: 0.8863, green: 0.898, blue: 0.9176, opacity: 1),
        dark: Color(red: 0.1686, green: 0.1843, blue: 0.2196, opacity: 1)
    )

    /// `--border-strong`
    static let borderStrong = Token(
        light: Color(red: 0.7961, green: 0.8196, blue: 0.851, opacity: 1),
        dark: Color(red: 0.2275, green: 0.2471, blue: 0.2941, opacity: 1)
    )

    /// `--code-background`
    static let codeBackground = Token(
        light: Color(red: 0.949, green: 0.9569, blue: 0.9686, opacity: 1),
        dark: Color(red: 0.1294, green: 0.1451, blue: 0.1765, opacity: 1)
    )

    /// `--code-text`
    static let codeText = Token(
        light: Color(red: 0.1412, green: 0.1608, blue: 0.1843, opacity: 1),
        dark: Color(red: 0.8431, green: 0.8588, blue: 0.8784, opacity: 1)
    )

    /// `--cursor-color`
    static let cursorColor = Token(
        light: Color(red: 0.2314, green: 0.4353, blue: 0.8314, opacity: 1),
        dark: Color(red: 0.4784, green: 0.6353, blue: 0.9686, opacity: 1)
    )

    /// `--graph-edge`
    static let graphEdge = Token(
        light: Color(red: 0.3608, green: 0.4, blue: 0.4471, opacity: 0.3),
        dark: Color(red: 0.6039, green: 0.6392, blue: 0.6824, opacity: 0.35)
    )

    /// `--graph-highlight`
    static let graphHighlight = Token(
        light: Color(red: 0.851, green: 0.5137, blue: 0.1412, opacity: 1),
        dark: Color(red: 0.8863, green: 0.7098, blue: 0.4118, opacity: 1)
    )

    /// `--graph-node`
    static let graphNode = Token(
        light: Color(red: 0.2314, green: 0.4353, blue: 0.8314, opacity: 1),
        dark: Color(red: 0.4784, green: 0.6353, blue: 0.9686, opacity: 1)
    )

    /// `--graph-node-attachment`
    static let graphNodeAttachment = Token(
        light: Color(red: 0.1333, green: 0.5255, blue: 0.3059, opacity: 1),
        dark: Color(red: 0.4941, green: 0.7843, blue: 0.5843, opacity: 1)
    )

    /// `--graph-node-tag`
    static let graphNodeTag = Token(
        light: Color(red: 0.6039, green: 0.4157, blue: 0.0745, opacity: 1),
        dark: Color(red: 0.8863, green: 0.7098, blue: 0.4118, opacity: 1)
    )

    /// `--graph-node-unresolved`
    static let graphNodeUnresolved = Token(
        light: Color(red: 0.6431, green: 0.6784, blue: 0.7216, opacity: 1),
        dark: Color(red: 0.4196, green: 0.4471, blue: 0.4902, opacity: 1)
    )

    /// `--h1-color`
    static let h1Color = Token(
        light: Color(red: 0.1216, green: 0.1373, blue: 0.1569, opacity: 1),
        dark: Color(red: 0.902, green: 0.9098, blue: 0.9216, opacity: 1)
    )

    /// `--h2-color`
    static let h2Color = Token(
        light: Color(red: 0.1216, green: 0.1373, blue: 0.1569, opacity: 1),
        dark: Color(red: 0.902, green: 0.9098, blue: 0.9216, opacity: 1)
    )

    /// `--h3-color`
    static let h3Color = Token(
        light: Color(red: 0.1216, green: 0.1373, blue: 0.1569, opacity: 1),
        dark: Color(red: 0.902, green: 0.9098, blue: 0.9216, opacity: 1)
    )

    /// `--h4-color`
    static let h4Color = Token(
        light: Color(red: 0.3608, green: 0.4, blue: 0.4471, opacity: 1),
        dark: Color(red: 0.6039, green: 0.6392, blue: 0.6824, opacity: 1)
    )

    /// `--h5-color`
    static let h5Color = Token(
        light: Color(red: 0.3608, green: 0.4, blue: 0.4471, opacity: 1),
        dark: Color(red: 0.6039, green: 0.6392, blue: 0.6824, opacity: 1)
    )

    /// `--h6-color`
    static let h6Color = Token(
        light: Color(red: 0.4902, green: 0.5255, blue: 0.5647, opacity: 1),
        dark: Color(red: 0.4196, green: 0.4471, blue: 0.4902, opacity: 1)
    )

    /// `--highlight-background`
    static let highlightBackground = Token(
        light: Color(red: 0.9412, green: 0.7451, blue: 0.3529, opacity: 0.5),
        dark: Color(red: 0.8863, green: 0.7098, blue: 0.4118, opacity: 0.32)
    )

    /// `--interactive-border`
    static let interactiveBorder = Token(
        light: Color(red: 0.5216, green: 0.5373, blue: 0.5686, opacity: 1),
        dark: Color(red: 0.4196, green: 0.4353, blue: 0.4667, opacity: 1)
    )

    /// `--link-color`
    static let linkColor = Token(
        light: Color(red: 0.2314, green: 0.4353, blue: 0.8314, opacity: 1),
        dark: Color(red: 0.4784, green: 0.6353, blue: 0.9686, opacity: 1)
    )

    /// `--link-unresolved-color`
    static let linkUnresolvedColor = Token(
        light: Color(red: 0.6039, green: 0.3725, blue: 0.502, opacity: 1),
        dark: Color(red: 0.6902, green: 0.4784, blue: 0.6039, opacity: 1)
    )

    /// `--selection-background`
    static let selectionBackground = Token(
        light: Color(red: 0.2314, green: 0.4353, blue: 0.8314, opacity: 0.2),
        dark: Color(red: 0.4784, green: 0.6353, blue: 0.9686, opacity: 0.28)
    )

    /// `--tag-background`
    static let tagBackground = Token(
        light: Color(red: 0.2314, green: 0.4353, blue: 0.8314, opacity: 0.12),
        dark: Color(red: 0.4784, green: 0.6353, blue: 0.9686, opacity: 0.16)
    )

    /// `--tag-color`
    static let tagColor = Token(
        light: Color(red: 0.1843, green: 0.3608, blue: 0.7098, opacity: 1),
        dark: Color(red: 0.6627, green: 0.7569, blue: 1, opacity: 1)
    )

    /// `--text-error`
    static let textError = Token(
        light: Color(red: 0.7843, green: 0.2157, blue: 0.2588, opacity: 1),
        dark: Color(red: 0.9137, green: 0.4157, blue: 0.4549, opacity: 1)
    )

    /// `--text-faint`
    static let textFaint = Token(
        light: Color(red: 0.4902, green: 0.5255, blue: 0.5647, opacity: 1),
        dark: Color(red: 0.4196, green: 0.4471, blue: 0.4902, opacity: 1)
    )

    /// `--text-muted`
    static let textMuted = Token(
        light: Color(red: 0.3608, green: 0.4, blue: 0.4471, opacity: 1),
        dark: Color(red: 0.6039, green: 0.6392, blue: 0.6824, opacity: 1)
    )

    /// `--text-normal`
    static let textNormal = Token(
        light: Color(red: 0.1216, green: 0.1373, blue: 0.1569, opacity: 1),
        dark: Color(red: 0.902, green: 0.9098, blue: 0.9216, opacity: 1)
    )

    /// `--text-on-accent`
    static let textOnAccent = Token(
        light: Color(red: 1, green: 1, blue: 1, opacity: 1),
        dark: Color(red: 0.0588, green: 0.0667, blue: 0.0824, opacity: 1)
    )

    /// `--text-success`
    static let textSuccess = Token(
        light: Color(red: 0.1333, green: 0.5255, blue: 0.3059, opacity: 1),
        dark: Color(red: 0.4941, green: 0.7843, blue: 0.5843, opacity: 1)
    )

    /// `--text-warning`
    static let textWarning = Token(
        light: Color(red: 0.6039, green: 0.4157, blue: 0.0745, opacity: 1),
        dark: Color(red: 0.8863, green: 0.7098, blue: 0.4118, opacity: 1)
    )

    // MARK: - Dimensions

    /// `--font-size-editor`
    static let fontSizeEditor: CGFloat = 16

    /// `--font-size-normal`
    static let fontSizeNormal: CGFloat = 15

    /// `--font-size-small`
    static let fontSizeSmall: CGFloat = 13

    /// `--font-size-smaller`
    static let fontSizeSmaller: CGFloat = 12

    /// `--radius-l`
    static let radiusL: CGFloat = 10

    /// `--radius-m`
    static let radiusM: CGFloat = 6

    /// `--radius-s`
    static let radiusS: CGFloat = 4

    /// `--space-1`
    static let space1: CGFloat = 4

    /// `--space-2`
    static let space2: CGFloat = 8

    /// `--space-3`
    static let space3: CGFloat = 12

    /// `--space-4`
    static let space4: CGFloat = 16

    /// `--space-5`
    static let space5: CGFloat = 24

    /// `--statusbar-height`
    static let statusbarHeight: CGFloat = 26

    /// `--tabbar-height`
    static let tabbarHeight: CGFloat = 36

    /// `--titlebar-height`
    static let titlebarHeight: CGFloat = 38
}

extension ShapeStyle where Self == Color {
    /// `Text("x").foregroundStyle(.token(.textMuted))`
    static func token(_ token: DesignTokens.Token) -> Color { token.color }
}
