#!/usr/bin/env node
//
// One version, in one place.
//
// The same number has to appear in four files: `package.json`, the Tauri
// bundle config, the Cargo workspace, and the UI that reports it to plugins
// and shows it in the About box. Four places means three chances to forget
// one, and the symptom is an installer that claims one version while the
// application claims another — which is exactly the kind of thing nobody
// notices until a user reports a bug against a version that was never built.
//
// `package.json` is the source. This script either writes the other three or
// checks that they agree:
//
//   node scripts/version.mjs         # write
//   node scripts/version.mjs --check # fail if any disagrees
//
// The check runs in CI beside the other generated-file checks, so the failure
// lands on the branch rather than at release time.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const checkOnly = process.argv.includes('--check');

const read = (path) => readFileSync(join(root, path), 'utf8');

const version = JSON.parse(read('package.json')).version;
if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version)) {
  console.error(
    `package.json has version "${version}", which is not a version Cargo and ` +
      'Tauri will both accept. Use MAJOR.MINOR.PATCH, optionally with a ' +
      '-prerelease suffix.',
  );
  process.exit(1);
}

/**
 * Each derived file: how to find the version in it, and how to write it back.
 *
 * Rewriting the matched line rather than re-serialising the whole file keeps
 * formatting, comments and key order exactly as they were — a version bump
 * should be a one-line diff.
 */
const DERIVED = [
  {
    path: 'src-tauri/tauri.conf.json',
    find: /("version"\s*:\s*")([^"]*)(")/,
    describe: 'the bundle version the installer reports',
  },
  {
    path: 'src-tauri/Cargo.toml',
    // The workspace's version, not a dependency's: anchored to the line that
    // follows `[workspace.package]`.
    find: /(\[workspace\.package\][\s\S]*?\nversion\s*=\s*")([^"]*)(")/,
    describe: 'the crate version',
  },
];

/** The generated module the UI imports. */
function versionModule(value) {
  return `/**
 * The application's version.
 *
 * Generated by scripts/version.mjs from package.json. Do not edit: change
 * package.json and run \`pnpm version:sync\`. CI fails if this file is stale.
 */

export const APP_VERSION = '${value}';
`;
}

const problems = [];
const written = [];

for (const file of DERIVED) {
  const text = read(file.path);
  const match = file.find.exec(text);
  if (!match) {
    problems.push(`${file.path}: could not find ${file.describe}`);
    continue;
  }

  const found = match[2];
  if (found === version) continue;

  if (checkOnly) {
    problems.push(`${file.path}: ${file.describe} is ${found}, but package.json says ${version}`);
  } else {
    const at = match.index + match[1].length;
    writeFileSync(
      join(root, file.path),
      text.slice(0, at) + version + text.slice(at + found.length),
    );
    written.push(`${file.path}: ${found} → ${version}`);
  }
}

const modulePath = 'src/version.ts';
const wanted = versionModule(version);
let current = null;
try {
  current = read(modulePath);
} catch {
  current = null;
}

if (current !== wanted) {
  if (checkOnly) {
    problems.push(
      current === null
        ? `${modulePath}: missing`
        : `${modulePath}: does not match package.json (${version})`,
    );
  } else {
    writeFileSync(join(root, modulePath), wanted);
    written.push(`${modulePath}: ${version}`);
  }
}

if (problems.length > 0) {
  console.error(`The version is not consistent (package.json says ${version}):\n`);
  for (const problem of problems) console.error(`  ${problem}`);
  console.error('\nRun: pnpm version:sync — then commit the result.');
  process.exit(1);
}

if (checkOnly) {
  console.log(`Version ${version} is consistent across every file that carries it.`);
} else if (written.length === 0) {
  console.log(`Version ${version} was already consistent; nothing to write.`);
} else {
  console.log(`Version ${version}:`);
  for (const line of written) console.log(`  ${line}`);
}
