/**
 * The application's version.
 *
 * Generated by scripts/version.mjs from package.json. Do not edit: change
 * package.json and run `pnpm version:sync`. CI fails if this file is stale.
 */

export const APP_VERSION = '0.1.0';
